apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pods-prefix
  namespace: default
spec:
  replicas: 50
  selector:
    matchLabels:
      app: nginx-pods-prefix
  template:
    metadata:
      labels:
        app: nginx-pods-prefix
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
