apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-efs
mountOptions:
- iam
parameters:
  directoryPerms: "700"
  fileSystemId: fs-
  provisioningMode: efs-ap
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
